### ISSUE TITLE
请问富文本编辑器能改造成 想 wps word 那种样式吗，每页分开的那种

### ISSUE THREAD

**Issue by xiangshu233** [ling0523/vue-editify#1]
![image](https://github.com/ling0523/vue-editify/assets/49575330/8b7569b2-62f3-459f-8f89-268940b742fc)

**Comment by ling0523** [comment]
感谢你的提出的issue，你说的是一篇文档分成好几页那种功能是吗，其实就是样式上分了几块。我会仔细去考虑你的问题。感谢建议

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月21日 16:49 |
| 收件人 | ling0523/vue-editify ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [ling0523/vue-editify] 请问富文本编辑器能改造成 想 wps word 那种样式吗，每页分开的那种 (Issue #1) |

image.png (view on web)

**Comment by so-better** [comment]
我准备把这个富文本编辑器使用ts+vue3组合式语法进行重构，到时候我会去实现你说的这个功能，感谢你的建议

**Comment by xiangshu233** [comment]
@ling0523 强的大佬，目前我们也处于调研阶段，市面上的 石墨、wps、腾讯文档的开放平台我们都咨询了，他们注重的多人协同，复杂的花里胡哨的效果他们不支持，到头来估计还要自己手撸，太难了这东西，这里有个分页的富文本可以参考下
https://github.com/Cassielxd/CassieEditor

**Comment by so-better** [comment]
好的，谢谢，我会尽快完成这个编辑器的改造，到时候会把你的建议考虑进去，十分感谢

**Comment by xiangshu233** [comment]
第一次接触这个东西，我感觉难度还是蛮大的 ，我只是个api调库侠 :)

**Comment by xiangshu233** [comment]
大佬效率牛皮 alex-editor 已经看到重构提交了，这是纯手撸的富文本编辑器啊（滑跪）。没有借助 ProseMirror 和 [Tiptap](https://tiptap.dev)吗，我全网都搜了一遍 这种分页比较难做，市面上所有富文本都没有开箱即用的分页功能，ckeditor 的分页还是收费的
[使用 CKEditor 5 分页功能克服所见即所得打印的挑战](https://ckeditor.com/blog/How-to-create-ready-to-print-documents-with-page-structure-in-WYSIWYG-editor---CKEditor-5-pagination-feature/]KEditor-5-pagination-feature/)

![image](https://github.com/ling0523/vue-editify/assets/49575330/49a8672a-b181-4532-b3b4-47e78d5e5699)
https://discuss.prosemirror.net/t/pagination/6078

**Comment by ling0523** [comment]
这个基础框架重构比较简单，vue-editify我得至少下周才能弄了。感谢关注

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月22日 14:39 |
| 收件人 | ling0523/vue-editify ***@***.***> |
| 抄送人 | ling0523 ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [ling0523/vue-editify] 请问富文本编辑器能改造成 想 wps word 那种样式吗，每页分开的那种 (Issue #1) |

大佬效率牛皮 alex-editor 已经看到重构提交了，这是纯手撸的富文本编辑器啊（滑跪）。没有借助 ProseMirror 和 Tiptap吗，我全网都搜了一遍 这种分页比较难做，市面上所有富文本都没有开箱即用的分页功能，ckeditor 的分页还是收费的
使用 CKEditor 5 分页功能克服所见即所得打印的挑战

image.png (view on web)
https://discuss.prosemirror.net/t/pagination/6078

**Comment by so-better** [comment]
alex-editor的重构比较简单，主要就是JS改TS，加上类型就差不多了😂，另外，我理解的这个分页，我感觉只是UI层面的效果吧，只是说一个编辑器的光标和选区，能够跨越多个区块，我没有想到那么复杂

**Comment by so-better** [comment]
其实ProseMirror和我这个定位差不多，都是底层的富文本编辑器框架， 所以我为了锻炼自己，尝试一下，就纯JS手写开发的。如果是基于ProseMirror，那也是vue-editify这类开箱即用的去做，只是我的vue-editify当然会基于我自己的alex-editor来开发啦，哈哈

**Comment by xiangshu233** [comment]
@ling0523 太强了，我就是个小趴菜。分页不是UI层面的，是那种所见即所得，网页展示什么样子打印就是什么样子
https://discuss.prosemirror.net/t/a4-pages-conceptual-guide/2901
https://blog.huli.tw/2021/06/12/paged-js-htmo-to-pdf-best-solution/
目前是打算基于 ProseMirror 和 [Tiptap](https://tiptap.dev/) 手写了😂

**Comment by xiangshu233** [comment]
大佬你的文档打不开了？

**Comment by so-better** [comment]
网站上次服务器崩了，我重启了😂，已经好了。然后我现在已经把这个编辑器基于TS和组合式语法进行重构了。目前正在研究你说的分页问题。是指编辑器内容，分成好几块区域展示对吧。“那种所见即所得，网页展示什么样子打印就是什么样子”这个抱歉我没太理解

**Comment by so-better** [comment]
其实就是类似于word文档，一页比如固定高度500px，当内容超出一页时，会显示在下一块区域内，每块区域都是可以随时编辑的，对吗

**Comment by so-better** [comment]
还有个理解就是，在上述的基础上，展示一个分页的按钮，标记页码，然后你翻页会显示不同页的内容，编辑的时候如果当前页满了，就自动到下一页编辑

**Comment by so-better** [comment]
我好像理解你的意思了，你是希望在一个网页上展现全部的内容，然后能够全部打印是吧。如果是这样的话，抱歉，这个可能暂时没法支持。但是editify有autoheight属性，可以自适应高度，这样整个网页就会展示全部内容了
