### ISSUE TITLE
cdn在线引入如何使用？实例名是啥？editify和Editify都不行

### ISSUE THREAD

**Issue by ajaxjs** [ling0523/vue-editify#2]
<script src="https://unpkg.com/vue-editify/lib/editify.umd.js"></script>

**Comment by so-better** [comment]
<img width="310" alt="image" src="https://github.com/so-better/vue-editify/assets/52031268/3c586d38-db20-41f6-9d7f-b3da2a79eafa">

是editify，具体可以在我网站看看使用方法,所有的内部方法通过editify引入，同时editify支持app.use进行全局注册，如果是局部注册，那就const {Editify} = window.editify，拿到的这个Editify就是vue组件

**Comment by ajaxjs** [comment]
我找到问题了，如果在editify之前引入monaco.editor 和 loader.js时，editify对象会不存在。

**Comment by ajaxjs** [comment]
另外，当编辑器内出现远程图片时，输入会出现闪动。
![ezgif-6-c1917ccc8f](https://github.com/so-better/vue-editify/assets/3959981/4f78bfe7-e7ed-4e45-bcfd-81e9699ea93a)

**Comment by so-better** [comment]
vue-editify底层依赖的alex-editor富文本编辑器框架也是我个人开发的，在这个编辑器框架中，每次渲染dom都是通过清空编辑器内容重新进行渲染的，因此动图和视频会有闪动效果，因为每次重新渲染视频或者动图都会重新播放。这个问题我考虑过使用类似于vue的diff算法来动态更新dom，但是效果不太好，当内容过多时进行比对的时候依然会很慢，反而js原生的innerHTML或者一次性append会加载快一点。这个后续看看是否能解决闪烁问题，但是不会影响你的编辑
