### ISSUE TITLE
编辑器设置disabled后，内容为纯英文状态下不会换行

### ISSUE THREAD

**Issue by 1234scarecrow** [ling0523/vue-editify#3]
造成这个问题的原因目前看来是因为只输入一长段不带格式的文字时，编辑器只会渲染一个span标签，如果是纯英文，span标签默认的word-break属性为normal，此时span并不能自动换行，所以就只会显示一行文字（中文状态下此默认属性不会影响换行）。修改此问题需要修改默认的word-break为break-all
注：只有disabled状态下会有这个问题，编辑模式下不会有，还没弄清楚

**Comment by so-better** [comment]
我看到了你这个问题，并且我自己去复现了一遍，这可能是浏览器的默认样式行为，在可编辑的div里span内容就算是纯英文也会换行，但是在禁用状态下（此时div不可编辑），span内的连续长英文不会换行，我们通常在写页面的时候其实也是有这种现象的。但是这个我个人目前觉得它是一种html/css的行为表现，如果在编辑器内部统一设置span的word-break这个可能不太好，你可以通过css覆盖设置span的word-break或者在自定义规则时设置styles，后续版本我会针对这个现象考虑一下是否进行适配

**Comment by so-better** [comment]
我已经在代码中将编辑区域设置了overflow-wrap:break-word，这个会在下个版本和其他内容一起发布，谢谢指正
